# Generated by Django 5.1.5 on 2025-02-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BF', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
