# Generated by Django 5.1.4 on 2025-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("BF", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
