# Generated by Django 5.1.4 on 2025-02-04 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BF", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favourite_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
