# Generated by Django 5.1.5 on 2025-02-12 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BF', '0005_address_pastorder_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_products',
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
