# Generated by Django 5.1.5 on 2025-02-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BF', '0006_remove_userprofile_favorite_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_products',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_profiles', to='BF.product'),
        ),
    ]
